---
- name: Default Config
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Render default configuration
      template:
        src: "/etc/Ansible/templates/device_config.j2"
        dest: "/etc/Ansible/temp_Configs/{{ inventory_hostname }}_default.conf"

    - name: Render interface configurations
      template:
        src: "/etc/Ansible/templates/interface_config.j2"
        dest: "/etc/Ansible/temp_Configs/{{ inventory_hostname }}_int.conf"

    - name: Configure device with config
      cli_config:
        config: "/etc/Ansible/temp_Configs/{{ inventory_hostname }}_default.conf"

    - name: Configure interfaces of device with config
      cli_config:
        config: "/etc/Ansible/temp_Configs/{{ inventory_hostname }}_int.conf"
