---
- name: Default Config
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: generate default config
      template:
        src: "/etc/ansible/jinja2-template/device.j2"
        dest: "/etc/ansible/tempfiles/{{ inventory_hostname }}_device.txt"
    - name: push configuration
      ios_config:
        src: /etc/ansible/tempfiles/{{ inventory_hostname }}_device.txt
        notify: do wr
        when: device.changed

    - name: generate interface config
      template:
        src: "/etc/ansible/jinja2-template/interface.j2"
        dest: "/etc/ansible/tempfiles/{{ inventory_hostname }}_interface.txt"
    - name: push configuration
      ios_config:
        src: /etc/ansible/tempfiles/{{ inventory_hostname }}_interface.txt
        notify: do wr
        when: interface.changed

  handlers:
    - name: do wr
      ios_command:
        commands: wr